### PR TITLE
fix: check for media_details before setting values

### PR DESCRIPTION
**Pull request by kantorcodes**
#### Problem
It appears a `TypeError` is thrown by this file every now and then
image

#### Description
checks for media_details before setting the width and height

### CODE REVIEW

**Review by tfrommen — APPROVED** [review]
Nice one, thanks! 🙌

**Comment by kantorcodes** [comment]
> Nice one, thanks! 🙌

Thanks for merging this one in! Would you also be able to tag this release?

**Comment by tfrommen** [comment]
@kantorcodes I did that last week already?

**Comment by kantorcodes** [comment]
> @kantorcodes I did that last week already? (But somehow I didn't push the tag. 😁 Fixed now.)

Thank you!!

**Pull request merged**
